package com.example.pieascoordinator;

import java.util.ArrayList;
import java.util.Date;

public class Data {

    private Data() {

    }

    public static ArrayList<Post> generatePosts() {
        ArrayList<Post> posts = new ArrayList<>();
        posts.add(new Post(1, "abdul", "First Post", "This is first post of this application and stored in Data class and generated by generatedPosts function.", new Date()));
        posts.add(new Post(2, "abdul", "Second Post", "This is second post of this application and stored in Data class and generated by generatedPosts function.", new Date()));
        posts.add(new Post(3, "abdul", "Third Post", "This is third post of this application and stored in Data class and generated by generatedPosts function.", new Date()));
        posts.add(new Post(4, "abdul", "Fourth Post", "This is fourth post of this application and stored in Data class and generated by generatedPosts function.", new Date()));
        posts.add(new Post(5, "abdul", "Fifth Post", "This is fifth post of this application and stored in Data class and generated by generatedPosts function.", new Date()));
        posts.add(new Post(6, "abdul", "Sixth Post", "This is sixth post of this application and stored in Data class and generated by generatedPosts function.", new Date()));
        posts.add(new Post(7, "abdul", "Seventh Post", "This is seventh post of this application and stored in Data class and generated by generatedPosts function.", new Date()));
        posts.add(new Post(8, "abdul", "Eight Post", "This is eight post of this application and stored in Data class and generated by generatedPosts function.", new Date()));
        posts.add(new Post(9, "abdul", "Ninth Post", "This is ninth post of this application and stored in Data class and generated by generatedPosts function.", new Date()));
        posts.add(new Post(10, "abdul", "Tenth Post", "This is tenth post of this application and stored in Data class and generated by generatedPosts function.", new Date()));
        return posts;
    }

    public static ArrayList<Comment> generateComments() {
        ArrayList<Comment> comments = new ArrayList<>();
        comments.add(new Comment(1, "abdul", "first comment for first post", new Date(), 1));
        comments.add(new Comment(2, "abdul", "second comment for first post", new Date(), 1));
        comments.add(new Comment(3, "abdul", "third comment for first post", new Date(), 1));
        comments.add(new Comment(4, "abdul", "first comment for fourth post", new Date(), 4));
        comments.add(new Comment(5, "abdul", "second comment for fourth post", new Date(), 4));
        comments.add(new Comment(6, "abdul", "third comment for fourth post", new Date(), 4));
        comments.add(new Comment(7, "abdul", "fourth comment for fourth post", new Date(), 4));
        comments.add(new Comment(8, "abdul", "first comment for second post", new Date(), 2));
        comments.add(new Comment(9, "abdul", "first comment for tenth post", new Date(), 10));
        comments.add(new Comment(10, "abdul", "first comment for seventh post", new Date(), 7));
        return comments;
    }

}
